#host: http://172.23.239.131:9092
host: 'localhost:9092'
server:
    port: 8187
spring:
    data:
        neo4j:
            password: root
            uri: bolt://35.154.116.88
            username: neo4j
