image:
  - maven:latest
  - openjdk:latest

before_script:
- apt-get update -qq && apt-get install

stages:
- build
- test


stage: build
  script:
  - mvn package


Test:
  stage: test
  script:
  -mvn test

