ribbon:
    eureka:
        enabled: false
server:

    ssl:
        key-store-type: PKCS12
        key-store: keystore.p12
        key-store-password: moviedb
        key-alias: tomcat
zuul:
    routes:
        login:
            path: /login/**
            url: http://35.154.116.88:8184
        registration:
            path: /register/**
            url: http://35.154.116.88:8181
        challenge:
            url: http://35.154.116.88:8180
        recommendation:
             path: /secure/**
             url: http://35.154.116.88:8186
        profile:
            path: /profile/**
            url: http://35.154.116.88:8185
        fileparser:
            path: /file/**
            url: http://35.154.116.88:8182
        voting:
            path: /vote/**
            url: http://35.154.116.88:8185
        compilation:
            path: /compile/**
            url: http://35.154.116.88:8183
        scoring:
            path: /score/**
            url: http://35.154.116.88:8189


# The format used for the keystore



security:
    require-ssl: false

management:
    security:
        enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.

logging:
    level:
        com.example.howtodoinjava: DEBUG
spring:
    application:
        name: zuul-gateway