ribbon:
    eureka:
        enabled: false
server:
    port: 8081
  
zuul:
    routes:
        login:
            
            url: http://localhost:8184
        register:
           
            url:  http://localhost:8181
        challenge:
            url:  http://localhost:8180
        recommendation:
             path: /secure/**
             url:  http://localhost:8186
        profile:
            
            url:  http://localhost:8185
        file:
           
            url: http://localhost:8182
        voting:
            path: /vote/**
            url: http://localhost:8185
        compilation:
            path: /compile/**
            url: http://localhost:8183/compile/
        scoring:
            path: /score/**
            url: http://localhost:8189


# The format used for the keystore



# security:
#     require-ssl: false

management:
    security:
        enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.

logging:
    level:
        com.example.howtodoinjava: DEBUG
spring:
    application:
        name: zuul-gateway
